### signup
@uri=http://localhost:4000/v1/api/

POST {{uri}}shop/signup
Content-Type: application/json
x-api-key: 5second

{
    "name": "Shop A",
    "email": "shopa2211w@yopmail.com",
    "password": "123123"
}

